### ISSUE TITLE
Build script uses old version of TLS

### ISSUE THREAD

**Issue by hallba** [hallba/BioModelAnalyzer#1]
Paket downloads don't currently run from the script, causing early termination ("Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel."). This is due to the site requiring a more up to date version of TLS. 

As a workaround, running this command allows the script to run

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by NikitaSkoblov** [comment]
Fixed in ffcaf99f254227f9177396d9bd00de7f26444291
