### ISSUE TITLE
Simulation initial value bug

### ISSUE THREAD

**Issue by hallba** [hallba/BioModelAnalyzer#2]
In the main UI, if using a variable with a large range, setting the initial value of a variable to >=4 sets the value to the top of the range. This occurs in a model that has granularity 4 otherwise (see attached).

Randomised values work as expected
[model 1.zip](https://github.com/hallba/BioModelAnalyzer/files/1838466/model.1.zip)

**Comment by NikitaSkoblov** [comment]
Fixed in a3d0a5a207422b5179eb90a0d1762477e6ccb550
