### ISSUE TITLE
Division by a variable can cause instability that depends on node ID. 

### ISSUE THREAD

**Issue by MClarke1991** [hallba/BioModelAnalyzer#20]
Target functions with a variable in a denominator will give nonsensical answers, dependent on node ID/order in which nodes are added to the network: 

If there is a set of three nodes _a_->_b_->_c_ where _a_ and _b_ can have range {0,1} or {0,2} but _c_ has range {0,2}, and _c_ has the target function `1/(1+var(b))`, or any target function that has a variable in the denominator, then _c_ will not stabilise. 

In this example c will have a lower bound of 2 and an upper bound of 1, i.e. the upper and lower bounds are the wrong way round. 

Furthermore, this only occurs if the node ID of _c_ > _b_. If the node ID of _b_ > _c_ then the network stabilises to the correct answer of 1. Attempting to use further testing gives a generic error message. I attach a minimal example of this "node_id.json" where the left triplet does not stabilise, while the right triplet does, and the target functions are identical. This is also seen when using BioCheckConsole.

**Comment by hallba** [comment]
Thanks for the bug report. This appears to be an issue in the range tightening code for division when the denominator uses a function of a variable. I've pushed a fix (2453d38)- please test.
