### ISSUE TITLE
Graph scaling for simulation doesn't respect exclusion

### ISSUE THREAD

**Issue by hallba** [hallba/BioModelAnalyzer#3]
Variables with a large range alter the scale of the resulting when simulations are viewed as a graph. This occurs even if the variables are excluded from the plot, leading to issues reading the simulation results. 

Simulation graphs should be scaled to the largest plotted variable

**Comment by NikitaSkoblov** [comment]
Fixed in b20b9959118221372e8da97e8d096f87921a3792
