### ISSUE TITLE
Network cannot be edited in GUI after cell name change

### ISSUE THREAD

**Issue by MClarke1991** [hallba/BioModelAnalyzer#6]
Sometimes, editing the name of a cell in a network will then stop any further interactions with the canvas. So one can change the type of interaction with the buttons on the top, but clicking on the canvas does not work, nor can one edit the nodes. A network json exported after this error occurs will still be corrupt upon import (cannot be imported) (example attached as a txt file as github does not support json: [corrupt.txt](https://github.com/hallba/BioModelAnalyzer/files/3044162/corrupt.txt))

If one then refreshes the tab containing BMA one will get the error

```
TypeError: e[a.ID] is undefined"
```

**Comment by NikitaSkoblov** [comment]
Fixed in 9e8f51eb6001d6db43f62aa667b44a04fd8cafb3
